### ISSUE TITLE
Deployment to staging and live not working

### ISSUE THREAD

**Issue by AaronWilton** [gbif/hp-new-zealand#28]
**Describe the bug**
I made a new release (v1.0.12*) but it is not being applied to the live site (and seeing no updates on staging either following commits)

**To Reproduce**
1. Go to 'gbif.org.nz'  the background image for the most recent post is missing also in the post and news page.
2. create release in github from master -> is not deployed

**Expected behavior**

**Screenshots**
![image](https://github.com/gbif/hp-new-zealand/assets/9813877/77522872-73a0-4787-ab27-735f2556eb88)

**Additional context**
Last release that was deployed is v1.0.11.
I initially thought it may have been the size or format of the background image so have changed these without success.
The site builds successfully when served locally.

Please let me know what I have done so I can avoid this in the future!

**Comment by MortenHofft** [comment]
For some reason you commits haven't been registered the last couple of days. Normally Github sends us a notification when there is a change. We then pull the code, builds and deploys it. Bit in this case that haven't happened. I do not know where in the chain the error happened.

I just tried to da a small edit to see if it was registered and it worked as it should.
https://github.com/gbif/hp-new-zealand/commits/master/

But none of your commits from Commits on Jun 12, 2024 was registered. (the last one has that little checkmark that means that the build worked, but that is only because I just manually triggered it).

**Comment by MattBlissett** [comment]
```
Jun 12 03:05:57 jenkins-vh.gbif.org jenkins[17855]: Caused: java.io.IOException: Failed to create a temporary file in /var/lib/jenkins/jobs/hp-new-zealand
```

At that moment the disk was full on the build server, and as it was 5am here we didn't fix it immediately.  It should work now, and we'll investigate whether we can improve things.

**Comment by AaronWilton** [comment]
@MattBlissett and @MortenHofft  - thanks deploying now
